### ISSUE TITLE
Mamba

### ISSUE THREAD

**Issue by spietras** [spietras/rules_conda#2]
Think about using [```mamba```](https://github.com/mamba-org/mamba) instead of ```conda```. That might speed things up.

**Comment by GabrielDougherty** [comment]
Sorry for the late reply, I was sick. Yes, that sounds like a good plan. I will begin work on this sometime this week. I will open a PR when I have something to show.

**Comment by spietras** [comment]
> Sorry for the late reply, I was sick.

No problem, hope you are feeling better now. Matter of fact, I was sick too D: 

> I will open a PR when I have something to show.

Great, looking forward to it. No pressure though, as there is not much going on anyway, so it's done when it's done. 

And while you are at it, take a look at this: https://github.com/mamba-org/mamba/issues/633. It might be that we need a little workaround to benefit from `mamba`. Namely, we probably need to create an empty environment first and then update it using the configuration file instead of doing it in one step.

**Comment by jiawen** [comment]
I recently discovered mamba as well and man is it fast!

Related - perhaps this should be a separate issue - any interest in adding support for installing using miniforge and/or mambaforge?

**Comment by spietras** [comment]
This is interesting. For now, let's keep the current flow (as `miniconda` should be supported anyway) and move it to a separate issue to discuss it there.
