### ISSUE TITLE
Miniforge

### ISSUE THREAD

**Issue by spietras** [spietras/rules_conda#20]
Consider adding support for [`miniforge`](https://github.com/conda-forge/miniforge). It's a `conda` installer similar to `miniconda`, but it's developed by the community and has `conda-forge` as the default channel. Some people might still want to use the usual `miniconda` installation, so we should make it possible to choose (probably with `miniconda` being the default).

This idea was originally brought up by @jiawen in https://github.com/spietras/rules_conda/issues/2#issuecomment-962496775

**Comment by jiawen** [comment]
Thanks for opening the new issue! I just poked around `conda.bzl` and it looks reasonably straightforward to add `miniforge` as another target.

If you haven't already started, I can probably find some cycles to give this a shot in a week or two.

**Comment by spietras** [comment]
If you are willing to try then sure, take a shot. Just keep in mind that #2 might change things up a little bit.
