### ISSUE TITLE
Release `0.1.0`

### ISSUE THREAD

**Issue by spietras** [spietras/rules_conda#29]
New major changes introduced lately: `miniforge` support with #21 and `mamba` support with #22. It might be a good time to release a new version of `rules_conda`.

Let's follow semantic versioning from now on and start with `0.1.0`.

**Comment by jiawen** [comment]
I just noticed that the API markdown is slightly broken due to some bad quoting: https://github.com/spietras/rules_conda/blob/main/docs/docs/usage/api.md

**Comment by spietras** [comment]
> I just noticed that the API markdown is slightly broken due to some bad quoting: https://github.com/spietras/rules_conda/blob/main/docs/docs/usage/api.md

It's on purpose, it's a flavor of markdown supported by [`mkdocs-material`](https://squidfunk.github.io/mkdocs-material). The docs you see there are actually being automatically deployed as a website on [Github Pages](https://spietras.github.io/rules_conda/usage/api)

**Comment by GabrielDougherty** [comment]
I would like to get in https://github.com/spietras/rules_conda/issues/34 before `0.1.0`

**Comment by spietras** [comment]
@GabrielDougherty yes, yes, I always update the `README` just before a new release (at least changing the version and hash), so I will address all these points. 

However, I'm quite busy right now, might get a little time on the weekend though. Now just letting yall know I'm alive 😛

**Comment by spietras** [comment]
Done
