### ISSUE TITLE
Example could not build due to the gap between release version and main branch

### ISSUE THREAD

**Issue by yibum** [spietras/rules_conda#32]
I see `rules_conda` now adds `mamba` support in the main branch, this is fantastic. 
However the example could not be built with the following error:
```bash
❯ ./bazelw run app
Starting local Bazel server and connecting to it...
ERROR: .../rules_conda/example/WORKSPACE:64:11: //external:conda: no such attribute 'conda_version' in 'load_conda_rule' rule
ERROR: .../rules_conda/example/WORKSPACE:64:11: //external:conda: no such attribute 'mamba_version' in 'load_conda_rule' rule
ERROR: .../rules_conda/example/WORKSPACE:64:11: //external:conda: no such attribute 'install_mamba' in 'load_conda_rule' rule
ERROR: .../rules_conda/example/WORKSPACE:72:13: //external:py2_env: no such attribute 'use_mamba' in 'conda_create_rule' rule
ERROR: .../rules_conda/example/WORKSPACE:82:13: //external:py3_env: no such attribute 'use_mamba' in 'conda_create_rule' rule
ERROR: error loading package 'external': Package 'external' contains errors
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

This is because the example `WORKSPACE` loads release version of `rules_conda` by default rather than that from the main branch, and new features like `conda_version` are added into example.
In this case, there will be a gap between the release version and the main branch.

I think it might be good to turn on `local_repository` by default, and leave the release version as another option in the example. Since it's higher chance for people cloning the repo first and then run the example, it could make the example playing experience more smooth.

I tried `git_repository` as well (by using commit zip), it could help bridge the gap, but `bazel` would clone the whole repo (including example 26M with bazelisk binary).

**Comment by GabrielDougherty** [comment]
I am fine with this change.

> I tried git_repository as well

btw, `git_repository` is deprecated and will print a deprecation warning. Also we would need to constantly re-pin the commit or make the build non-reproducible if we went that route, since main is constantly changing. I prefer using `local_repository` as you have done.

**Comment by spietras** [comment]
Right, good idea. Let's make `local_repository` the default one and have the `http_archive` commented out.
